openapi: "3.0.0"
info:
  title: "API"
  version: "1.0.0"
servers:
    - url: "http://localhost:8080"
paths:
  /fruits:
    get:
      summary: "Get all fruits"
      responses:
        '200':
          description: "A list of fruits"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Fruit"
    post:
      summary: "Create a fruit"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FruitNew"

      responses:
        '201':
          description: "Fruit created"
          content:
            application/json:
              schema:
                type: "string"
components:
    schemas:
        Fruit:
          allOf:
            - $ref: "#/components/schemas/FruitNew"
            - required:
                - id
                - name
              properties:
                id:
                  type: integer
                  description: "fruit id"

        FruitNew:
          required:
            - name
          properties:
            name:
              type: string
              description: "fruit name"
            icon:
              type: string
              description: "fruit icon ex: 🍎"
