services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: air
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: ixeti
      MYSQL_PASSWORD: sample
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d